### ISSUE TITLE
Check for perl before loading BioNetGen files

### ISSUE THREAD

**Issue by luciansmith** [biosimulators/Biosimulators_utils#103]
If perl isn't on the user's system, loading a BioNetGen file will fail with "The system cannot find the file specified".  It will appear as if the bionetgen file itself was unable to be found.  However, the problem is actually that when BNG initializes itself, it runs a perl command, which thows the FileNotFoundError if perl isn't present.  It might be nice to check for the existence of perl before trying to load the file.  (As it was, I assumed that the file in question was the bionetgen file, which was not the case.)

**Comment by jonrkarr** [comment]
This is really a BioNetGen issue. I recommend posting this to [RuleWorld/PyBioNetGen](https://github.com/RuleWorld/PyBioNetGen)

**Comment by luciansmith** [comment]
Oh, I guess I got the wrong repository; https://github.com/RuleWorld/bionetgen/issues/244  I assume they'll transfer the issue when they get to it.

I don't know how responsive BNG is to this sort of thing, so figured I'd go ahead and post it here as a low-priority enhancement in the meantime.

**Comment by jonrkarr** [comment]
I could add this here, but I'd prefer not to assume that PyBioNetGen necessarily relies on Perl since they're moving toward a separate BioNetGen library that won't be implemented with Perl.

Sanan has been fairly responsive to feedback.

**Comment by luciansmith** [comment]
Fair enough!  Let's just go with the filed issue, then, and drop this.

**Comment by jonrkarr** [comment]
This related to open issues I submitted:
- RuleWorld/PyBioNetGen#22
- RuleWorld/PyBioNetGen#8
- ASinanSaglam/PyBioNetGen#5
- ASinanSaglam/PyBioNetGen#6

I created a new issue for this: 
- RuleWorld/PyBioNetGen#41
