### ISSUE TITLE
Allow more-specific algorithm substitution.

### ISSUE THREAD

**Issue by luciansmith** [biosimulators/Biosimulators_utils#105]
When validating biomodels models, I get the following error a lot:

NotImplementedError: Algorithm substitution for "steady state method" (http://www.biomodels.net/kisao/KISAO#KISAO_0000407) for policy SAME_VARIABLES is not supported.

(See, for example, biomodels BIOMD0000000498/BIOMD0000000498.sedml)

KiSAO term 407 is the generic steady state algorithm, so it is likely that the problem is that substituting a more-specific algorithm for the generic one has not been implemented.  I could be wrong, and I could also be wrong about what repository the error message came from!  But this was my best guess.

**Comment by jonrkarr** [comment]
Not much has been done with steady state. To start, it would be helpful to get code from Frank Bergmann for use with COPASI. There's minimal bandwidth for now.

**Comment by luciansmith** [comment]
Fixed in libkisao.
