### ISSUE TITLE
SED-ML generated by CellML utils raises type error 

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulators/Biosimulators_utils#106]
The underlying calls to libSedml raise a value error when a Sed-ML document is generated using the CellML utilities method. The value for the "number of steps" is a float instead of the expected int. Changing the following two lines to have number of steps equal to ```10``` instead of ```10.``` resolves the issue.  

https://github.com/biosimulators/Biosimulators_utils/blob/c99d27c32bf4deb5b0348e5fb8470de5e88b7904/biosimulators_utils/model_lang/cellml/utils.py#L103

https://github.com/biosimulators/Biosimulators_utils/blob/c99d27c32bf4deb5b0348e5fb8470de5e88b7904/biosimulators_utils/model_lang/cellml/utils.py#L183

@jonrkarr is the proposed changed correct? Or am I missing something regarding the usage?

**Comment by jonrkarr** [comment]
It sounds like this is not being used as intended.
