### ISSUE TITLE
Allow element math to have attribute "id" in CellML files

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulators/Biosimulators_utils#108]
Many of the cellML files in the physiome repository fail validation because the "Math" elements contains "id" attributes. The model file fail validation with the message ```117.0: Invalid attribute id for element math```

@jonrkarr Is this something that we could change to a warning, or would you recommend that this be handled by physiome?

**Comment by bilalshaikh42** [comment]
Looking closer at how validation is actually performed, it seems that this is something that the physiome models should correct since the math elements are defined with the MathML schema which is linked from the CellML schema https://github.com/biosimulators/Biosimulators_utils/blob/dev/biosimulators_utils/model_lang/cellml/cellml1.0.rng

**Comment by jonrkarr** [comment]
These errors are determined by CellML's own validation. Please submit GutHub issues for these issues to the Physiome repository.

**Comment by jonrkarr** [comment]
The schema that you linked is simply copied from cellml.org.

**Comment by bilalshaikh42** [comment]
Closing as this should be fixed in physiome/cellml
