### ISSUE TITLE
The sed-ml validator doesn't accept empty lists of variables / parameters in SetValue.

### ISSUE THREAD

**Issue by danv61** [biosimulators/Biosimulators_utils#113]
I receive the message: "...is not a valid SED-ML file: (20103 [Error]) No empty lists, listOfVariables cannot be empty"

Although sedml L1V3 specifications state that empty lists of variables / parameters are legal:
"2.1.7.7 listOfVariables ... The listOfVariables is optional and may contain zero to many variables."

Same for listOfParameters

**Comment by jonrkarr** [comment]
This is a libSED-ML issue. Please create an issue at https://github.com/fbergmann/libSEDML.
