### ISSUE TITLE
Deployed runBioSimulations API not returning `resultsSize`

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_utils#12]
The dev deployment returns `resultsSize`
https://dispatch.biosimulations.dev/run/5fdda8358b0da07b332ffa5a

but the deploy deployment does not
https://run.api.biosimulations.org/run/5fdd4ae450632203a037459a

Does https://run.api.biosimulations.org need to be re-deployed?

**Comment by bilalshaikh42** [comment]
I was able to get the results size after running a new simulation. The
older simulations may not have the results size if they were submitted
before the fix. Can you let me know which combine archive is not giving the
results?

Best
Bilal

**Comment by jonrkarr** [comment]
That makes sense.
