### ISSUE TITLE
get_pubmed_central_open_access_graphics leaves tar.gz file in directory.

### ISSUE THREAD

**Issue by luciansmith** [biosimulators/Biosimulators_utils#129]
The function get_pubmed_central_open_access_graphics grabs a .tar.gz file from pubmedcentral, unzips it, and returns a list of the thumbnails therein.  It would be nice if it also cleaned up after itself, and removed the original .tar.gz file.

**Comment by b-tao** [comment]
Hi, I would be willing to fix this. How should I start

**Comment by luciansmith** [comment]
I would find the get_pubmed_central_open_access_graphics function, look where it downloads the file, add code that makes a note of the filename, then look ahead to where it unzips the file, and add code to delete the .gz file after that.

**Comment by b-tao** [comment]
Ok, I made the necessary changes on my local branch. However, it denies me access to set my local branch's upstream. Would it be possible to assign me this issue and give me permission to push a branch and PR.

**Comment by luciansmith** [comment]
I don't think I have admin access to the repository.  @eagmon or @jonrkarr , can you add @b-tao ?

**Comment by jonrkarr** [comment]
Added to the developers team. He needs to approve the invite.

**Comment by b-tao** [comment]
Thank you so much for the quick response. I was able to create a branch for this issue and linked it to a PR to view. Let me know if there is anything else I can do.
