### ISSUE TITLE
Container exits with success code if no sedml is found

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulators/Biosimulators_utils#26]
Example: https://run.biosimulations.dev/simulations/603d35ff5d7132300f9edd13#tab=log

The container exited successfully, resulting in the slurm job being successful as well. While true, the user might expect this to be a failure.

**Comment by jonrkarr** [comment]
We could treat this an error.

**Comment by jonrkarr** [comment]
I switched this from a warning to an error. 

This is released with version `0.1.40` of this package. I'll update the Docker images for the simulation tools next.

**Comment by jonrkarr** [comment]
The Docker images should update over the next 30 minutes or so.
