### ISSUE TITLE
Not all SED-ML containers need children

### ISSUE THREAD

**Issue by luciansmith** [biosimulators/Biosimulators_utils#58]
(Not sure if this is the best place to report this; feel free to move it to a better place if there is one.)

On your list of validation rules that Biosimulators checks for SED-ML files, there's the item:

```
\item Each container element has at least one child:
    \begin{itemize}[labelwidth=0pt]
    \item Repeated tasks have at least one subtask.
    \item Reports have at least one data set.
    \item 2D plots have at least one curve.
    \item 3D plots have at least one surface.
    \end{itemize}
```

However, this list is incorrect.  

* Repeated tasks must indeed have at least one subtask but must also contain at least one Range.  
* Reports and plots are valid SED-ML even if they're empty.  It would be fine to issue a warning in those situations, however, given Biosimulator's context.

For L1v4, the additional restrictions apply:
A ParameterEstimationTask must have at least one AdjustableParameter, and at least one FitExperiment.
A FitExperiment must have at least one FitMapping.

For all other lists, it is perfectly legal to have a ListOfX with zero children, and is functionally equivalent (but may not be annotationally equivalent) to having no child ListOfX in the first place.

**Comment by jonrkarr** [comment]
Moving the L1V4 tasks to #59.
