### ISSUE TITLE
Validate that metadata is about URIs that begin with `http://omex-library.org/` prefix

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_utils#70]
Issue found by @bilalshaikh42.

This cannot currently be done because libOmexMeta currently automatically inserts this prefix. This can be resolved once sys-bio/libOmexMeta#138 is resolved.

**Comment by bilalshaikh42** [comment]
@all-contributors add @bilalshaikh42  for finding bugs

**Comment by jonrkarr** [comment]
Done
