### ISSUE TITLE
Add to_json and from_json method to JournalArticle class

### ISSUE THREAD

**Issue by bilalshaikh42** [biosimulators/Biosimulators_utils#78]
I have a small hack function to save the journal article to a json file to avoid calling the NCBI API too much. It would be helpful to incorporate this into the class

**Comment by bilalshaikh42** [comment]
I am silly. JournalArticle is a data class and I can just use the asDict method

**Comment by jonrkarr** [comment]
For caching HTTP queries, I like `requests-cache`. 

The Entrez methods are probably easiest to cache externally. One option is something like https://pypi.org/project/diskcache/.

**Comment by jonrkarr** [comment]
Dataclass is nice. Unfortunately, I wasn't aware of this when we started.
